name: ci

on: [deployment_status]

jobs:
  cypress-run:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        with:
          record: true
          browser: chrome
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
      - name: save videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: save screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
